function [fitresult, gof] = createFit(x, Y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'Yfit' fit:
%      X Input : x
%      Y Output: Y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-May-2024 10:33:34


%% Fit: 'Yfit'.
[xData, yData] = prepareCurveData( x, Y );

% Set up fittype and options.
ft = fittype( '(3.52e-13*(l^2)/(8*3.1415*1.25e-9*a*0.1e-4))*(erfc(0.1e-4.*l./(2.*sqrt(1.25e-9.*x))+sqrt(k.*x))*exp(0.1e-4*l*sqrt(k/1.25e-9)) + erfc(0.1e-4.*l./(2.*sqrt(1.25e-9.*x))-sqrt(k.*x))*exp(-0.1e-4*l*sqrt(k/1.25e-9)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0.005 0 1];
opts.StartPoint = [0.22 0.223811939491137 3];
opts.Upper = [1 Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Yfit' );
h = plot( fitresult, xData, yData );
legend( h, 'Y vs. x', 'Yfit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'Y', 'Interpreter', 'none' );
grid on


